# xbuilder docker-compose 示例 - 开发环境
# 包含开发依赖服务 (数据库、缓存等)
name: ${PROJECT_NAME:-app}-dev
services:
  # ─────────────────────────────────────────────────────────────
  # 应用服务
  # ─────────────────────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME:-app}-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - DEBUG=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-app}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      # 挂载源码目录 (热重载)
      - .:/app:cached
      # 排除不需要挂载的目录
      - /app/node_modules
      - /app/vendor
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - dev-network

  # ─────────────────────────────────────────────────────────────
  # PostgreSQL 数据库
  # ─────────────────────────────────────────────────────────────
  db:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME:-app}-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-app}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # 初始化脚本
      - ./scripts/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

  # ─────────────────────────────────────────────────────────────
  # Redis 缓存
  # ─────────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME:-app}-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - dev-network

volumes:
  postgres-data:
  redis-data:

networks:
  dev-network:
    driver: bridge
